name: Upload Python Package to PyPI

on:
  release:
    types: [ published, edited ]

permissions:
  contents: read

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Validate exts version matching
        run: |
          python -m pip install tomli
          python hooks/version_check.py

      - name: Install dependencies
        run: |
          python -m pip install build cibuildwheel

      - name: Build pure python package
        run: python -m build

      - name: Build binary python package
        run: |
          cd ./pyballistic.exts
          python -m build --sdist --outdir ../dist
          cibuildwheel --output-dir ../dist
          cd ..

      - name: List ./dist
        run: ls ./dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Download artifacts (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: ./dist-ubuntu

      - name: Download artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: dist-windows-latest
          path: ./dist-windows

      - name: Download artifacts (macOS 13)
        uses: actions/download-artifact@v4
        with:
          name: dist-macos-13
          path: ./dist-macos-13

      - name: Download artifacts (macOS 14)
        uses: actions/download-artifact@v4
        with:
          name: dist-macos-14
          path: ./dist-macos-14

      - name: Inspect downloaded artifacts
        run: |
          echo "Ubuntu:" && ls -la ./dist-ubuntu || true
          echo "Windows:" && ls -la ./dist-windows || true
          echo "macOS 13:" && ls -la ./dist-macos-13 || true
          echo "macOS 14:" && ls -la ./dist-macos-14 || true

      - name: Combine artifacts
        shell: bash
        run: |
          mkdir -p dist
          cp ./dist-ubuntu/* dist/ || true
          cp ./dist-windows/* dist/ || true
          cp ./dist-macos-13/* dist/ || true
          cp ./dist-macos-14/* dist/ || true
          echo "Combined dists:" && ls -la dist || true
          # Fail fast if nothing combined
          if [ -z "$(ls -A dist 2>/dev/null)" ]; then
            echo "No distributions found in combined dist folder" >&2
            exit 1
          fi

      - name: List ./dist
        run: ls ./dist

      - name: Split dists for core and exts
        shell: bash
        run: |
          mkdir -p dist-core dist-exts
          # Route files based on filename (handles dot vs underscore)
          shopt -s nullglob
          for f in dist/*; do
            base="$(basename "$f")"
            if [[ "$base" == pyballistic.exts-* || "$base" == pyballistic_exts-* ]]; then
              cp "$f" dist-exts/
            elif [[ "$base" == pyballistic-* ]]; then
              cp "$f" dist-core/
            fi
          done
          echo "Core dists:" && ls -la dist-core || true
          echo "Exts dists:" && ls -la dist-exts || true
          # Sanity checks
          if [ -z "$(ls -A dist-core 2>/dev/null)" ]; then
            echo "No core distributions were found after split" >&2
            exit 1
          fi
          if [ -z "$(ls -A dist-exts 2>/dev/null)" ]; then
            echo "No extensions distributions were found after split" >&2
            exit 1
          fi

      - name: Publish core package (pyballistic)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist-core
          skip-existing: true

      - name: Publish extensions package (pyballistic.exts)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist-exts
          skip-existing: true
