name: Upload Python Package to test PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Validate exts version matching
        run: |
          python -m pip install tomli
          python hooks/version_check.py

      - name: Install dependencies
        run: |
          python -m pip install build cibuildwheel

      - name: Build pure python package
        run: python -m build

      - name: Build binary python package
        run: |
          cd ./pyballistic.exts
          python -m build --sdist --outdir ../dist
          cibuildwheel --output-dir ../dist
          cd ..

      - name: List ./dist
        run: ls ./dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write

    steps:
      - name: Download artifacts (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: ./dist-ubuntu

      - name: Download artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: dist-windows-latest
          path: ./dist-windows

      - name: Download artifacts (macOS 13)
        uses: actions/download-artifact@v4
        with:
          name: dist-macos-13
          path: ./dist-macos-13

      - name: Download artifacts (macOS 14)
        uses: actions/download-artifact@v4
        with:
          name: dist-macos-14
          path: ./dist-macos-14

      - name: Combine artifacts
        run: |
          mkdir -p dist
          cp ./dist-ubuntu/* dist/ || true
          cp ./dist-windows/* dist/ || true
          cp ./dist-macos-13/* dist/ || true
          cp ./dist-macos-14/* dist/ || true
          echo "Combined dists:" && ls -la dist || true
          if [ -z "$(ls -A dist 2>/dev/null)" ]; then
            echo "No distributions found in combined dist folder" >&2
            exit 1
          fi

      - name: List ./dist
        run: ls ./dist

      - name: Split dists for core and exts
        shell: bash
        run: |
          set -e
          mkdir -p dist-core dist-exts
          echo "Splitting combined dists..."
          echo "Combined dist contents:" && ls -la dist || true
          # Core patterns
          cp dist/pyballistic-[0-9]* dist-core/ 2>/dev/null || true
          cp dist/pyballistic-*.whl dist-core/ 2>/dev/null || true
          # Exts patterns: dot/underscore/hyphen
          cp dist/pyballistic.exts-[0-9]* dist-exts/ 2>/dev/null || true
          cp dist/pyballistic-exts-[0-9]* dist-exts/ 2>/dev/null || true
          cp dist/pyballistic_exts-*.whl dist-exts/ 2>/dev/null || true
          echo "Core dists:" && ls -la dist-core || true
          echo "Exts dists:" && ls -la dist-exts || true
          if [ -z "$(ls -A dist-core 2>/dev/null)" ]; then
            echo "No core distributions were found after split" >&2
            echo "Core patterns:" && ls -la dist/pyballistic-[0-9]* dist/pyballistic-*.whl 2>/dev/null || true
            exit 1
          fi
          if [ -z "$(ls -A dist-exts 2>/dev/null)" ]; then
            echo "No extensions distributions were found after split" >&2
            echo "Exts patterns:" && ls -la dist/pyballistic.exts-[0-9]* dist/pyballistic-exts-[0-9]* dist/pyballistic_exts-*.whl 2>/dev/null || true
            exit 1
          fi

      - name: Publish core package (TestPyPI)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist-core

      - name: Publish extensions package (TestPyPI)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist-exts
